export const AUTH_INITIALIZED = 'AUTH_INITIALIZED';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CLEAR_ERRORS = 'AUTH_CLEAR_ERRORS';
export const AUTH_CLEAR_REDIRECT = 'AUTH_CLEAR_REDIRECT';
